name: Set up Nix
description: Install Nix and configure the GitHub Actions Nix cache.

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v22
      with:
        determinate: false
        extra-conf: |
          auto-allocate-uids = true
          extra-experimental-features = auto-allocate-uids cgroups
          extra-system-features = uid-range

    - name: Setup magic Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v13
      with:
        use-flakehub: false
